### ISSUE TITLE
无法评测python3

### ISSUE THREAD

**Issue by fearlessxjdx** [NJUPTAAA/NOJ_JudgeServer#3]
试了几个其他语言是正常的，但python3.7会报错

![image](https://user-images.githubusercontent.com/17431574/174096992-dfb548c0-43a7-4457-83e9-31e08348cb46.png)

compile.log
```plain
FATAL [2022-06-16 14:45:45] [/tmp/Judger/src/child.c:164]Error: System errno: No such file or directory; Internal errno: EXECVE_FAILED
```
judge_server.log
```plain
2022-06-16 14:45:45,996 ERROR 
Traceback (most recent call last):
  File "/code/server.py", line 195, in server
    ret = {"err": None, "data": getattr(JudgeServer, path)(**data)}
  File "/code/server.py", line 99, in judge
    output_dir=submission_dir)
  File "/code/compiler.py", line 45, in compile
    raise CompileError("Compiler runtime error, info: %s" % json.dumps(result))
exception.CompileError
```

**Comment by fearlessxjdx** [comment]
应该是因为 noj Extension 没更新的原因，不是这边的 bug

**Comment by ZsgsDesign** [comment]
Sorry for the delay. The latest version of JudgerServer supports `0.18.0`, while `0.17.4` supports previous version of Judge Server.

https://github.com/ZsgsDesign/NOJ/blob/91b7d8448a09db50b70c06c706e6dc171b439b6c/app/Babel/Extension/noj/compiler/1647594391.json#L14-L17
